---
name: Module-CPANTS-Site
version: 0.75
author:
  - 'Thomas Klausner, <domm@cpan.org>'
abstract: Catalyst based application
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.7000
  Catalyst::Model::DBIC::Schema: 0.16
  Catalyst::Plugin::ConfigLoader: 0.11
  Catalyst::Plugin::Static::Simple: 0.14
  Catalyst::View::TT: 0.23
  DBD::SQLite: 1.14
  DBIx::Class: 0.07000
  Module::CPANTS::Analyse: 0.75
  Module::CPANTS::ProcessCPAN: 0.70
  Template::Plugin::Number::Format: 1.02
  version: 0.73
build_requires:
  File::HomeDir: 0.66
provides:
  Module::CPANTS::Site:
    file: lib/Module/CPANTS/Site.pm
    version: 0.75
  Module::CPANTS::Site::Controller::Author:
    file: lib/Module/CPANTS/Site/Controller/Author.pm
  Module::CPANTS::Site::Controller::Dist:
    file: lib/Module/CPANTS/Site/Controller/Dist.pm
  Module::CPANTS::Site::Controller::Highscores:
    file: lib/Module/CPANTS/Site/Controller/Highscores.pm
  Module::CPANTS::Site::Controller::Kwalitee:
    file: lib/Module/CPANTS/Site/Controller/Kwalitee.pm
  Module::CPANTS::Site::Controller::Root:
    file: lib/Module/CPANTS/Site/Controller/Root.pm
  Module::CPANTS::Site::Model::DBIC:
    file: lib/Module/CPANTS/Site/Model/DBIC.pm
  Module::CPANTS::Site::Model::Kwalitee:
    file: lib/Module/CPANTS/Site/Model/Kwalitee.pm
  Module::CPANTS::Site::View::TT:
    file: lib/Module/CPANTS/Site/View/TT.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
