abstract: Catalyst based application
author: 'domm,,,'
distribution_type: module
generated_by: Module::Install version 0.54
license: perl
name: Module-CPANTS-Site
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.64
  Module::CPANTS::Analyse: 0.60
  Module::CPANTS::ProcessCPAN: 0.60
version: 0.60
